#### This file is divided into two parts. In the first one the data frame obtained by the Scraper is cleaned and being prepared for its analysis which is conducted in the second part.

### Part 1 - Cleaning

In [3]:
import pandas as pd

#### After importing necessary packages we upload the csv file that was created by the class ScraperURL

In [138]:
table = pd.read_csv('C:/Users/jancv/Player_stats.csv')

In [148]:
table.head()

,player,nationality,position,squad,age,birth_year,games,games_starts,minutes,goals,assists,pens_made,pens_att,cards_yellow,cards_red,goals_per90,assists_per90,goals_assists_per90,goals_pens_per90,goals_assists_pens_per90
0,Marko Alvir,CRO,MF,Viktoria Plzeň,26,1994.0,9.0,0.0,116,0.0,0.0,0.0,0.0,2.0,0.0,0.00,0.0,0.00,0.00,0.00
1,Emmanuel Antwi,GHA,DF,Příbram,24,1996.0,8.0,2.0,273,2.0,0.0,0.0,0.0,0.0,0.0,0.66,0.0,0.66,0.66,0.66
2,Oleksandr Azatskyi,UKR,DF,Baník Ostrava,26,1994.0,3.0,0.0,26,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00
3,Pavol Bajza,SVK,GK,Slovácko,29,1991.0,6.0,6.0,540,0.0,0.0,0.0,0.0,1.0,0.0,0.00,0.0,0.00,0.00,0.00
4,Jakub Barac,CZE,MF,Slovan Liberec,24,1996.0,3.0,1.0,80,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00

#### 1) FIrst look at the data reveals that the first column can be excluded as it only stores the indexes. 

#### 2) Further, we want to find out whether our data frame cointains NaN values. If it is the case, the observation will be dropped.

#### 3) Moreover, we can see that a column 'nationality' needs to be edited in that we are only interested in the 3-letter abbreviation.    The same holds for the age, where the days are not very informative at all, therefore only the age in years will be taken into consideration.

In [149]:
table = table.iloc[:,1:]

False

In [143]:
table.isnull().any().any()

In [150]:
table = table.dropna()

In [145]:
nationality = []
for nat in table['nationality']:
    nationality.append(nat[3:])
table['nationality'] = nationality

In [146]:
age = []
for ag in table['age']:
    age.append(int(ag[:2]))
table['age'] = age

#### We found out that at this moment every column where integers or floats are expected do satisfy this condition with the exception of 'minutes'. Thus, we have to convert it from a column of strings to  integer.

In [147]:
minutes = []
for minute in table['minutes']:
    minute = minute.replace(",","")
    minutes.append(int(minute))

table['minutes'] = minutes

In [129]:
table.head()

,player,nationality,position,squad,age,birth_year,games,games_starts,minutes,goals,assists,pens_made,pens_att,cards_yellow,cards_red,goals_per90,assists_per90,goals_assists_per90,goals_pens_per90,goals_assists_pens_per90
0,Marko Alvir,CRO,MF,Viktoria Plzeň,26,1994.0,9.0,0.0,116,0.0,0.0,0.0,0.0,2.0,0.0,0.00,0.0,0.00,0.00,0.00
1,Emmanuel Antwi,GHA,DF,Příbram,24,1996.0,8.0,2.0,273,2.0,0.0,0.0,0.0,0.0,0.0,0.66,0.0,0.66,0.66,0.66
2,Oleksandr Azatskyi,UKR,DF,Baník Ostrava,26,1994.0,3.0,0.0,26,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00
3,Pavol Bajza,SVK,GK,Slovácko,29,1991.0,6.0,6.0,540,0.0,0.0,0.0,0.0,1.0,0.0,0.00,0.0,0.00,0.00,0.00
4,Jakub Barac,CZE,MF,Slovan Liberec,24,1996.0,3.0,1.0,80,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00

In [ ]:
table.to_csv('Final_Player_Table.csv')

#### Our data frame is now ready to be analyzed.

### Part 2 - Analysis